Repository SovereignCloudStack/minutes, pull requests merged in 2024-02, with the labels that each got.

#462 Add iaas call 2024-02-14
  iaas/20240214.md
Labels: IaaS

#461 Add sig-standardization/20240208.md
  sig-standardization/20240208.md
Labels: SCS is standardized, SCS-VP10

#450 Feat/add iamsec 202401
  iam/20240110.md
  iam/20240117.md
  iam/20240131.md
Labels: housekeeping

#443 Little script to search md for pics.
  tools/check_links.sh
Labels: housekeeping

#472 Add SIG community minutes 2024-02-19
  sig-community/20240219.md
Labels: housekeeping
